version: '3'
services:
  azure-vote-back:
    image: redis
    container_name: vote-back
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./vote
    image: vote-front
    container_name: vote-front
    environment:
      REDIS: vote-back
    ports:
        - "8080:80"
