jobs:
# jobs for the provision-gke-kubernetes-cluster app

  - name: build_frontend_image
    type: runSh
    steps:
      - IN: ship_voting_app_redis_gitRepo
        switch: off
      - IN: gke_cliConfig
      - OUT: front_img
      - TASK:
        # invoke a script that provisions the GKE cluster named test-cluster
        - script: |
            pushd $(shipctl get_resource_state "ship_voting_app_redis_gitRepo")/ship-vote
              export IMG_TAG=master.$BUILD_NUMBER
              export IMG_REF=gcr.io/fair-future-183201/vote:$IMG_TAG
              docker build -t $IMG_REF .
              gcloud docker -- push $IMG_REF
              shipctl put_resource_state front_img "versionName" "$IMG_TAG"
            popd

  - name: deploy_test
    type: runSh
    steps:
      - IN: ship_voting_app_redis_gitRepo
        switch: off
      - IN: gke_cliConfig
      - IN: front_img
      - IN: test_params
      - IN: kube_cluster
      - OUT: relstate
      - OUT: teststate
      - TASK:
        # invoke a script that provisions the GKE cluster named test-cluster
        - script: |
            pushd $(shipctl get_resource_state "ship_voting_app_redis_gitRepo")/kubernetes-manifests
              export FE_TAG=$(shipctl get_resource_version_name "front_img")
              cp ./ship_vote_all_in_one_redis.yml.template ./release.template.yml
              shipctl post_resource_state "relstate" "FE_TAG" $FE_TAG
              shipctl refresh_file_to_out_path ./release.template.yml relstate

              cp ./ship_vote_all_in_one_redis.yml.template ./test_deploy_spec.yml
              shipctl replace ./test_deploy_spec.yml
              shipctl refresh_file_to_out_path ./test_deploy_spec.yml teststate

              gcloud container clusters get-credentials $KUBE_CLUSTER_POINTER_SOURCENAME --zone $KUBE_CLUSTER_POINTER_REGION
              # delete previous deployments and services
              kubectl delete deployment $FE_LABEL 2>/dev/null || echo ""
              kubectl delete deployment $BE_LABEL 2>/dev/null || echo ""
              kubectl delete service $FE_LABEL 2>/dev/null || echo ""
              kubectl delete service $BE_LABEL 2>/dev/null || echo ""

              kubectl create -o json -f ./test_deploy_spec.yml > kube_output.json
              cat kube_output.json
            popd

  - name: deploy_prod
    type: runSh
    steps:
      - IN: deploy_test
        switch: off
      - IN: gke_cliConfig
      - IN: prod_params
      - IN: kube_cluster
      - IN: relstate
      - OUT: prodstate
      - TASK:
        # invoke a script that provisions the GKE cluster named test-cluster
        - script: |
            shipctl copy_resource_file_from_state relstate release.template.yml .
            cp ./release.template.yml ./prod_deploy_spec.yml
            export FE_TAG=$(eval echo "$"$(shipctl get_resource_version_key "relstate" "FE_TAG"))
            shipctl replace ./prod_deploy_spec.yml
            shipctl refresh_file_to_out_path ./prod_deploy_spec.yml prodstate

            gcloud container clusters get-credentials $KUBE_CLUSTER_POINTER_SOURCENAME --zone $KUBE_CLUSTER_POINTER_REGION
            # delete previous deployments and services
            kubectl delete deployment $FE_LABEL 2>/dev/null || echo ""
            kubectl delete deployment $BE_LABEL 2>/dev/null || echo ""
            kubectl delete service $FE_LABEL 2>/dev/null || echo ""
            kubectl delete service $BE_LABEL 2>/dev/null || echo ""

            kubectl create -o json -f ./prod_deploy_spec.yml > kube_output.json
            cat kube_output.json
